development:
  adapter: mysql2
  encoding: utf8
  database: holiday_development
  pool: 5
  username: root
  password: admin

test:
  adapter: sqlite3
  database: db/test.sqlite3

production: 
  adapter: mysql2
  encoding: utf8
  database: holiday_production
  pool: 5
  username: root
  password: Mage114n
